version: '3'

services:
  tomcat:
    container_name: tomcat
    build: ./
    image: rogerranium/tomcat
    networks:
      - datalink
    depends_on:
      - pgdb
    ports:
      - "8080:8080"
      - "61000:61000"
      - "80:80"
      - "443:443"
    expose:
      - 61000
    environment:
      _JAVA_OPTIONS: "-Xms256m -Xmx384m -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=61000"

  pgdb:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ./postgres/postgres.env
    volumes:
       - postgresDB:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - datalink

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    env_file:
      - ./postgres/postgres.env
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - datalink
    restart: unless-stopped

networks:
  datalink:
    driver: bridge

volumes:
    postgresDB:
    pgadmin: